/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './constants/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#0e0e12',
        surface: '#1a1a22',
        'surface-raised': '#22222e',
        border: '#2a2a38',
        primary: '#f5f0e8',
        secondary: '#9990a8',
        muted: '#5a5568',
        amber: '#e8a020',
        'amber-light': '#f5b840',
        'amber-dark': '#c07818',
        green: '#4caf82',
        teal: '#38b2ac',
        red: '#e05555',
        'keycap-face': '#f5f0e8',
        'keycap-depth': '#c8c0b0',
        'keycap-depth-accent': '#c07818',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '40px',
        '3xl': '48px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '28px',
        full: '999px',
      },
      fontFamily: {
        jakarta: ['PlusJakartaSans-Regular'],
        'jakarta-medium': ['PlusJakartaSans-Medium'],
        'jakarta-semibold': ['PlusJakartaSans-SemiBold'],
        'jakarta-bold': ['PlusJakartaSans-Bold'],
        'jakarta-extrabold': ['PlusJakartaSans-ExtraBold'],
      },
      fontSize: {
        xs: ['10px', { lineHeight: '14px' }],
        sm: ['12px', { lineHeight: '16px' }],
        base: ['14px', { lineHeight: '20px' }],
        md: ['16px', { lineHeight: '22px' }],
        lg: ['18px', { lineHeight: '26px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['32px', { lineHeight: '40px' }],
        '4xl': ['44px', { lineHeight: '52px' }],
      },
    },
  },
  plugins: [],
};
